name: Unit Test - Unity

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

  workflow_dispatch:
  
jobs:
  UnitTest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: make -C 3_Implementation/
      - name: test
        run: make test -C 3_Implementation/
